version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
        - 27017:27017

  selenium:
    image: selenium/standalone-firefox
    ports:
      - 4444:4444

  notebook:
    build: .
    ports:
     - "8888:8888"
    command: ["pipenv", "run", "jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
    volumes:
      - ./:/home/dev/code/
      
